# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paudit.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import penums_pb2
import pvisit_pb2
import pstat_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='paudit.proto',
  package='comphealth',
  serialized_pb='\n\x0cpaudit.proto\x12\ncomphealth\x1a\x0cpenums.proto\x1a\x0cpvisit.proto\x1a\x0bpstat.proto\"q\n\x06PAudit\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x1e\n\x05stats\x18\x04 \x02(\x0b\x32\x0f.comphealth.AGG\x12)\n\x0cvtype_subset\x18\x05 \x03(\x0b\x32\x13.comphealth.VSubset\"K\n\x07VSubset\x12 \n\x05vtype\x18\x01 \x02(\x0e\x32\x11.comphealth.ETYPE\x12\x1e\n\x05stats\x18\x02 \x02(\x0b\x32\x0f.comphealth.AGG')




_PAUDIT = _descriptor.Descriptor(
  name='PAudit',
  full_name='comphealth.PAudit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='comphealth.PAudit.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='comphealth.PAudit.dataset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stats', full_name='comphealth.PAudit.stats', index=2,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vtype_subset', full_name='comphealth.PAudit.vtype_subset', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=182,
)


_VSUBSET = _descriptor.Descriptor(
  name='VSubset',
  full_name='comphealth.VSubset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vtype', full_name='comphealth.VSubset.vtype', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stats', full_name='comphealth.VSubset.stats', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=184,
  serialized_end=259,
)

_PAUDIT.fields_by_name['stats'].message_type = pstat_pb2._AGG
_PAUDIT.fields_by_name['vtype_subset'].message_type = _VSUBSET
_VSUBSET.fields_by_name['vtype'].enum_type = penums_pb2._ETYPE
_VSUBSET.fields_by_name['stats'].message_type = pstat_pb2._AGG
DESCRIPTOR.message_types_by_name['PAudit'] = _PAUDIT
DESCRIPTOR.message_types_by_name['VSubset'] = _VSUBSET

class PAudit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAUDIT

  # @@protoc_insertion_point(class_scope:comphealth.PAudit)

class VSubset(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VSUBSET

  # @@protoc_insertion_point(class_scope:comphealth.VSubset)


# @@protoc_insertion_point(module_scope)
