# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: penums.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='penums.proto',
  package='comphealth',
  serialized_pb=_b('\n\x0cpenums.proto\x12\ncomphealth*?\n\x05\x45TYPE\x12\x06\n\x02IP\x10\x00\x12\x06\n\x02\x45\x44\x10\x01\x12\x06\n\x02\x41S\x10\x02\x12\x07\n\x03OUT\x10\x03\x12\x05\n\x01H\x10\x04\x12\x05\n\x01O\x10\x05\x12\x07\n\x03\x41LL\x10\x06*,\n\x03SEX\x12\x08\n\x04MALE\x10\n\x12\n\n\x06\x46\x45MALE\x10\x0b\x12\x0f\n\x0bSEX_UNKNOWN\x10\x0c*/\n\x05\x44\x45\x41TH\x12\t\n\x05\x41LIVE\x10\x1e\x12\x08\n\x04\x44\x45\x41\x44\x10\x1f\x12\x11\n\rDEATH_UNKNOWN\x10 *^\n\x05PAYER\x12\x0c\n\x08MEDICARE\x10)\x12\x0c\n\x08MEDICAID\x10*\x12\x0b\n\x07PRIVATE\x10+\x12\x08\n\x04SELF\x10,\x12\t\n\x05OTHER\x10-\x12\r\n\tP_UNKNOWN\x10.\x12\x08\n\x04\x46REE\x10/*]\n\x04RACE\x12\t\n\x05WHITE\x10\x33\x12\t\n\x05\x42LACK\x10\x34\x12\x0c\n\x08HISPANIC\x10\x35\x12\t\n\x05\x41SIAN\x10\x36\x12\n\n\x06NATIVE\x10\x37\x12\x0b\n\x07R_OTHER\x10\x38\x12\r\n\tR_UNKNOWN\x10\x39*\xb3\x01\n\x06SOURCE\x12\r\n\tS_ROUTINE\x10=\x12\x0e\n\nS_HOSPITAL\x10>\x12\t\n\x05S_SNF\x10?\x12\n\n\x06S_HOME\x10@\x12\x0b\n\x07S_OTHER\x10\x41\x12\x08\n\x04S_ED\x10\x42\x12\r\n\tS_UNKNOWN\x10\x43\x12\x0b\n\x07S_COURT\x10\x44\x12\x12\n\rS_TEXAS_PSYCH\x10\xd8\x04\x12\x15\n\x10S_TEXAS_CRITICAL\x10\xd9\x04\x12\x15\n\x10S_TEXAS_INTERNAL\x10\xda\x04*\xa4\x01\n\x0b\x44ISPOSITION\x12\r\n\tD_ROUTINE\x10G\x12\x0e\n\nD_HOSPITAL\x10H\x12\t\n\x05\x44_SNF\x10I\x12\n\n\x05\x44_ICF\x10\xbd\x05\x12\n\n\x06\x44_HOME\x10J\x12\x0b\n\x07\x44_DEATH\x10K\x12\x0b\n\x07\x44_OTHER\x10L\x12\r\n\tD_UNKNOWN\x10M\x12\t\n\x05\x44_AMA\x10N\x12\x12\n\x0e\x44_UNKNOWNALIVE\x10O\x12\x0b\n\x07\x44_COURT\x10\x46*D\n\x03\x44NR\x12\n\n\x06\x44NR_NO\x10P\x12\x0b\n\x07\x44NR_YES\x10Q\x12\x0f\n\x0b\x44NR_UNKNOWN\x10R\x12\x13\n\x0f\x44NR_UNAVAILABLE\x10S*\x19\n\x05\x43TYPE\x12\x07\n\x03ICD\x10Z\x12\x07\n\x03\x43PT\x10[*K\n\x04PZIP\x12\x0b\n\x07Z_FIRST\x10\x65\x12\x0c\n\x08Z_SECOND\x10\x66\x12\x0b\n\x07Z_THIRD\x10g\x12\x0c\n\x08Z_FOURTH\x10h\x12\r\n\tZ_UNKNOWN\x10i')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ETYPE = _descriptor.EnumDescriptor(
  name='ETYPE',
  full_name='comphealth.ETYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='H', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='O', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALL', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=28,
  serialized_end=91,
)
_sym_db.RegisterEnumDescriptor(_ETYPE)

ETYPE = enum_type_wrapper.EnumTypeWrapper(_ETYPE)
_SEX = _descriptor.EnumDescriptor(
  name='SEX',
  full_name='comphealth.SEX',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MALE', index=0, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEX_UNKNOWN', index=2, number=12,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=93,
  serialized_end=137,
)
_sym_db.RegisterEnumDescriptor(_SEX)

SEX = enum_type_wrapper.EnumTypeWrapper(_SEX)
_DEATH = _descriptor.EnumDescriptor(
  name='DEATH',
  full_name='comphealth.DEATH',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALIVE', index=0, number=30,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEAD', index=1, number=31,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEATH_UNKNOWN', index=2, number=32,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=139,
  serialized_end=186,
)
_sym_db.RegisterEnumDescriptor(_DEATH)

DEATH = enum_type_wrapper.EnumTypeWrapper(_DEATH)
_PAYER = _descriptor.EnumDescriptor(
  name='PAYER',
  full_name='comphealth.PAYER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MEDICARE', index=0, number=41,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDICAID', index=1, number=42,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIVATE', index=2, number=43,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELF', index=3, number=44,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=4, number=45,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P_UNKNOWN', index=5, number=46,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FREE', index=6, number=47,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=188,
  serialized_end=282,
)
_sym_db.RegisterEnumDescriptor(_PAYER)

PAYER = enum_type_wrapper.EnumTypeWrapper(_PAYER)
_RACE = _descriptor.EnumDescriptor(
  name='RACE',
  full_name='comphealth.RACE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WHITE', index=0, number=51,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLACK', index=1, number=52,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HISPANIC', index=2, number=53,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASIAN', index=3, number=54,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NATIVE', index=4, number=55,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='R_OTHER', index=5, number=56,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='R_UNKNOWN', index=6, number=57,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=284,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_RACE)

RACE = enum_type_wrapper.EnumTypeWrapper(_RACE)
_SOURCE = _descriptor.EnumDescriptor(
  name='SOURCE',
  full_name='comphealth.SOURCE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S_ROUTINE', index=0, number=61,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_HOSPITAL', index=1, number=62,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_SNF', index=2, number=63,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_HOME', index=3, number=64,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_OTHER', index=4, number=65,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_ED', index=5, number=66,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_UNKNOWN', index=6, number=67,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_COURT', index=7, number=68,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_TEXAS_PSYCH', index=8, number=600,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_TEXAS_CRITICAL', index=9, number=601,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_TEXAS_INTERNAL', index=10, number=602,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=380,
  serialized_end=559,
)
_sym_db.RegisterEnumDescriptor(_SOURCE)

SOURCE = enum_type_wrapper.EnumTypeWrapper(_SOURCE)
_DISPOSITION = _descriptor.EnumDescriptor(
  name='DISPOSITION',
  full_name='comphealth.DISPOSITION',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='D_ROUTINE', index=0, number=71,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_HOSPITAL', index=1, number=72,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_SNF', index=2, number=73,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_ICF', index=3, number=701,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_HOME', index=4, number=74,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_DEATH', index=5, number=75,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_OTHER', index=6, number=76,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_UNKNOWN', index=7, number=77,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_AMA', index=8, number=78,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_UNKNOWNALIVE', index=9, number=79,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D_COURT', index=10, number=70,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=562,
  serialized_end=726,
)
_sym_db.RegisterEnumDescriptor(_DISPOSITION)

DISPOSITION = enum_type_wrapper.EnumTypeWrapper(_DISPOSITION)
_DNR = _descriptor.EnumDescriptor(
  name='DNR',
  full_name='comphealth.DNR',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DNR_NO', index=0, number=80,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DNR_YES', index=1, number=81,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DNR_UNKNOWN', index=2, number=82,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DNR_UNAVAILABLE', index=3, number=83,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=728,
  serialized_end=796,
)
_sym_db.RegisterEnumDescriptor(_DNR)

DNR = enum_type_wrapper.EnumTypeWrapper(_DNR)
_CTYPE = _descriptor.EnumDescriptor(
  name='CTYPE',
  full_name='comphealth.CTYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ICD', index=0, number=90,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CPT', index=1, number=91,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=798,
  serialized_end=823,
)
_sym_db.RegisterEnumDescriptor(_CTYPE)

CTYPE = enum_type_wrapper.EnumTypeWrapper(_CTYPE)
_PZIP = _descriptor.EnumDescriptor(
  name='PZIP',
  full_name='comphealth.PZIP',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Z_FIRST', index=0, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Z_SECOND', index=1, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Z_THIRD', index=2, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Z_FOURTH', index=3, number=104,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Z_UNKNOWN', index=4, number=105,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=825,
  serialized_end=900,
)
_sym_db.RegisterEnumDescriptor(_PZIP)

PZIP = enum_type_wrapper.EnumTypeWrapper(_PZIP)
IP = 0
ED = 1
AS = 2
OUT = 3
H = 4
O = 5
ALL = 6
MALE = 10
FEMALE = 11
SEX_UNKNOWN = 12
ALIVE = 30
DEAD = 31
DEATH_UNKNOWN = 32
MEDICARE = 41
MEDICAID = 42
PRIVATE = 43
SELF = 44
OTHER = 45
P_UNKNOWN = 46
FREE = 47
WHITE = 51
BLACK = 52
HISPANIC = 53
ASIAN = 54
NATIVE = 55
R_OTHER = 56
R_UNKNOWN = 57
S_ROUTINE = 61
S_HOSPITAL = 62
S_SNF = 63
S_HOME = 64
S_OTHER = 65
S_ED = 66
S_UNKNOWN = 67
S_COURT = 68
S_TEXAS_PSYCH = 600
S_TEXAS_CRITICAL = 601
S_TEXAS_INTERNAL = 602
D_ROUTINE = 71
D_HOSPITAL = 72
D_SNF = 73
D_ICF = 701
D_HOME = 74
D_DEATH = 75
D_OTHER = 76
D_UNKNOWN = 77
D_AMA = 78
D_UNKNOWNALIVE = 79
D_COURT = 70
DNR_NO = 80
DNR_YES = 81
DNR_UNKNOWN = 82
DNR_UNAVAILABLE = 83
ICD = 90
CPT = 91
Z_FIRST = 101
Z_SECOND = 102
Z_THIRD = 103
Z_FOURTH = 104
Z_UNKNOWN = 105


DESCRIPTOR.enum_types_by_name['ETYPE'] = _ETYPE
DESCRIPTOR.enum_types_by_name['SEX'] = _SEX
DESCRIPTOR.enum_types_by_name['DEATH'] = _DEATH
DESCRIPTOR.enum_types_by_name['PAYER'] = _PAYER
DESCRIPTOR.enum_types_by_name['RACE'] = _RACE
DESCRIPTOR.enum_types_by_name['SOURCE'] = _SOURCE
DESCRIPTOR.enum_types_by_name['DISPOSITION'] = _DISPOSITION
DESCRIPTOR.enum_types_by_name['DNR'] = _DNR
DESCRIPTOR.enum_types_by_name['CTYPE'] = _CTYPE
DESCRIPTOR.enum_types_by_name['PZIP'] = _PZIP


# @@protoc_insertion_point(module_scope)
