# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pn3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import penums_pb2
import pvisit_pb2
import pstat_pb2
import pn1_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pn3.proto',
  package='comphealth',
  serialized_pb=_b('\n\tpn3.proto\x12\ncomphealth\x1a\x0cpenums.proto\x1a\x0cpvisit.proto\x1a\x0bpstat.proto\x1a\tpn1.proto\"\xe8\x02\n\x06VEntry\x12\x0b\n\x03key\x18\x0b \x02(\t\x12\x13\n\x0binitial_key\x18\x01 \x02(\t\x12\x0f\n\x07sub_key\x18\x02 \x02(\t\x12\x0f\n\x07\x64\x61taset\x18\x03 \x01(\t\x12\r\n\x05\x64\x65lta\x18\x08 \x01(\x05\x12 \n\x07initial\x18\x04 \x02(\x0b\x32\x0f.comphealth.AGG\x12\x1c\n\x03sub\x18\x05 \x02(\x0b\x32\x0f.comphealth.AGG\x12#\n\x06\x64\x65ltah\x18\x06 \x02(\x0b\x32\x13.comphealth.IntHist\x12\'\n\ndeltaweekh\x18\x0c \x02(\x0b\x32\x13.comphealth.IntHist\x12)\n\nprovenance\x18\x07 \x03(\x0b\x32\x15.comphealth.Exclusion\x12*\n\rinitial_ktype\x18\t \x02(\x0e\x32\x13.comphealth.KEYTYPE\x12&\n\tsub_ktype\x18\n \x02(\x0e\x32\x13.comphealth.KEYTYPE\"\x8c\x02\n\x05VNode\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\"\n\x05ktype\x18\x02 \x02(\x0e\x32\x13.comphealth.KEYTYPE\x12\x0f\n\x07\x64\x61taset\x18\x03 \x01(\t\x12\x1c\n\x03\x61ll\x18\x04 \x02(\x0b\x32\x0f.comphealth.AGG\x12#\n\ndischarged\x18\x05 \x01(\x0b\x32\x0f.comphealth.AGG\x12$\n\x0btransferred\x18\x06 \x01(\x0b\x32\x0f.comphealth.AGG\x12\x1d\n\x04\x64ied\x18\x07 \x01(\x0b\x32\x0f.comphealth.AGG\x12)\n\nprovenance\x18\x08 \x03(\x0b\x32\x15.comphealth.Exclusion\x12\x0e\n\x06linked\x18\t \x02(\x08*K\n\x07KEYTYPE\x12\r\n\x08N3_ICDPR\x10\xd0\x05\x12\n\n\x05N3_DX\x10\xd2\x05\x12\x0b\n\x06N3_DRG\x10\xd3\x05\x12\x0b\n\x06N3_CPT\x10\xd4\x05\x12\x0b\n\x06N3_ALL\x10\xd5\x05')
  ,
  dependencies=[penums_pb2.DESCRIPTOR,pvisit_pb2.DESCRIPTOR,pstat_pb2.DESCRIPTOR,pn1_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_KEYTYPE = _descriptor.EnumDescriptor(
  name='KEYTYPE',
  full_name='comphealth.KEYTYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='N3_ICDPR', index=0, number=720,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='N3_DX', index=1, number=722,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='N3_DRG', index=2, number=723,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='N3_CPT', index=3, number=724,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='N3_ALL', index=4, number=725,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=711,
  serialized_end=786,
)
_sym_db.RegisterEnumDescriptor(_KEYTYPE)

KEYTYPE = enum_type_wrapper.EnumTypeWrapper(_KEYTYPE)
N3_ICDPR = 720
N3_DX = 722
N3_DRG = 723
N3_CPT = 724
N3_ALL = 725



_VENTRY = _descriptor.Descriptor(
  name='VEntry',
  full_name='comphealth.VEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='comphealth.VEntry.key', index=0,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initial_key', full_name='comphealth.VEntry.initial_key', index=1,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_key', full_name='comphealth.VEntry.sub_key', index=2,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='comphealth.VEntry.dataset', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta', full_name='comphealth.VEntry.delta', index=4,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initial', full_name='comphealth.VEntry.initial', index=5,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub', full_name='comphealth.VEntry.sub', index=6,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deltah', full_name='comphealth.VEntry.deltah', index=7,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deltaweekh', full_name='comphealth.VEntry.deltaweekh', index=8,
      number=12, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='provenance', full_name='comphealth.VEntry.provenance', index=9,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initial_ktype', full_name='comphealth.VEntry.initial_ktype', index=10,
      number=9, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=720,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_ktype', full_name='comphealth.VEntry.sub_ktype', index=11,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=720,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=438,
)


_VNODE = _descriptor.Descriptor(
  name='VNode',
  full_name='comphealth.VNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='comphealth.VNode.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ktype', full_name='comphealth.VNode.ktype', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=720,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='comphealth.VNode.dataset', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all', full_name='comphealth.VNode.all', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discharged', full_name='comphealth.VNode.discharged', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transferred', full_name='comphealth.VNode.transferred', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='died', full_name='comphealth.VNode.died', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='provenance', full_name='comphealth.VNode.provenance', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linked', full_name='comphealth.VNode.linked', index=8,
      number=9, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=709,
)

_VENTRY.fields_by_name['initial'].message_type = pstat_pb2._AGG
_VENTRY.fields_by_name['sub'].message_type = pstat_pb2._AGG
_VENTRY.fields_by_name['deltah'].message_type = pstat_pb2._INTHIST
_VENTRY.fields_by_name['deltaweekh'].message_type = pstat_pb2._INTHIST
_VENTRY.fields_by_name['provenance'].message_type = pn1_pb2._EXCLUSION
_VENTRY.fields_by_name['initial_ktype'].enum_type = _KEYTYPE
_VENTRY.fields_by_name['sub_ktype'].enum_type = _KEYTYPE
_VNODE.fields_by_name['ktype'].enum_type = _KEYTYPE
_VNODE.fields_by_name['all'].message_type = pstat_pb2._AGG
_VNODE.fields_by_name['discharged'].message_type = pstat_pb2._AGG
_VNODE.fields_by_name['transferred'].message_type = pstat_pb2._AGG
_VNODE.fields_by_name['died'].message_type = pstat_pb2._AGG
_VNODE.fields_by_name['provenance'].message_type = pn1_pb2._EXCLUSION
DESCRIPTOR.message_types_by_name['VEntry'] = _VENTRY
DESCRIPTOR.message_types_by_name['VNode'] = _VNODE
DESCRIPTOR.enum_types_by_name['KEYTYPE'] = _KEYTYPE

VEntry = _reflection.GeneratedProtocolMessageType('VEntry', (_message.Message,), dict(
  DESCRIPTOR = _VENTRY,
  __module__ = 'pn3_pb2'
  # @@protoc_insertion_point(class_scope:comphealth.VEntry)
  ))
_sym_db.RegisterMessage(VEntry)

VNode = _reflection.GeneratedProtocolMessageType('VNode', (_message.Message,), dict(
  DESCRIPTOR = _VNODE,
  __module__ = 'pn3_pb2'
  # @@protoc_insertion_point(class_scope:comphealth.VNode)
  ))
_sym_db.RegisterMessage(VNode)


# @@protoc_insertion_point(module_scope)
