# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pn4.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import penums_pb2
import pvisit_pb2
import pstat_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pn4.proto',
  package='comphealth',
  serialized_pb=_b('\n\tpn4.proto\x12\ncomphealth\x1a\x0cpenums.proto\x1a\x0cpvisit.proto\x1a\x0bpstat.proto\"\xd7\x04\n\x06NEntry\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05index\x18\x02 \x02(\t\x12\x0b\n\x03sub\x18\x03 \x02(\t\x12\r\n\x05\x63ount\x18\x0c \x02(\x05\x12\x15\n\rlinked_visits\x18\r \x02(\x05\x12\x17\n\x0funlinked_visits\x18\x0e \x02(\x05\x12\x10\n\x08patients\x18\x0f \x02(\x05\x12-\n\x10index_first_days\x18\x10 \x02(\x0b\x32\x13.comphealth.IntHist\x12+\n\x0esub_first_days\x18\x14 \x02(\x0b\x32\x13.comphealth.IntHist\x12\x14\n\x0cindex_visits\x18\x11 \x02(\x05\x12\x12\n\nsub_visits\x18\x12 \x02(\x05\x12\x1b\n\x13intersection_visits\x18\x13 \x02(\x05\x12\x1b\n\x13patient_index_first\x18\x15 \x02(\x05\x12\x19\n\x11patient_sub_first\x18\x17 \x02(\x05\x12\x1c\n\x03\x64xh\x18\x18 \x03(\x0b\x32\x0f.comphealth.DXI\x12$\n\x0bprimary_prh\x18\x19 \x03(\x0b\x32\x0f.comphealth.KVI\x12\x1c\n\x03prh\x18\x1a \x03(\x0b\x32\x0f.comphealth.KVI\x12\x1c\n\x03\x65xh\x18\x1b \x03(\x0b\x32\x0f.comphealth.KVI\x12\x1d\n\x04\x64rgh\x18\x1c \x03(\x0b\x32\x0f.comphealth.KVI\x12.\n\x15\x66irst_inpatient_visit\x18\x1d \x01(\x0b\x32\x0f.comphealth.AGG\x12)\n\x0bvtype_count\x18\x1e \x03(\x0b\x32\x14.comphealth.N4VCOUNT\"9\n\x08N4VCOUNT\x12\t\n\x01k\x18\x01 \x02(\t\x12\n\n\x02IP\x18\x02 \x01(\x05\x12\n\n\x02\x45\x44\x18\x03 \x01(\x05\x12\n\n\x02\x41S\x18\x04 \x01(\x05')
  ,
  dependencies=[penums_pb2.DESCRIPTOR,pvisit_pb2.DESCRIPTOR,pstat_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NENTRY = _descriptor.Descriptor(
  name='NEntry',
  full_name='comphealth.NEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='comphealth.NEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='comphealth.NEntry.index', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub', full_name='comphealth.NEntry.sub', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='comphealth.NEntry.count', index=3,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linked_visits', full_name='comphealth.NEntry.linked_visits', index=4,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unlinked_visits', full_name='comphealth.NEntry.unlinked_visits', index=5,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='patients', full_name='comphealth.NEntry.patients', index=6,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index_first_days', full_name='comphealth.NEntry.index_first_days', index=7,
      number=16, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_first_days', full_name='comphealth.NEntry.sub_first_days', index=8,
      number=20, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index_visits', full_name='comphealth.NEntry.index_visits', index=9,
      number=17, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_visits', full_name='comphealth.NEntry.sub_visits', index=10,
      number=18, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intersection_visits', full_name='comphealth.NEntry.intersection_visits', index=11,
      number=19, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='patient_index_first', full_name='comphealth.NEntry.patient_index_first', index=12,
      number=21, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='patient_sub_first', full_name='comphealth.NEntry.patient_sub_first', index=13,
      number=23, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dxh', full_name='comphealth.NEntry.dxh', index=14,
      number=24, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='primary_prh', full_name='comphealth.NEntry.primary_prh', index=15,
      number=25, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prh', full_name='comphealth.NEntry.prh', index=16,
      number=26, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exh', full_name='comphealth.NEntry.exh', index=17,
      number=27, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drgh', full_name='comphealth.NEntry.drgh', index=18,
      number=28, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first_inpatient_visit', full_name='comphealth.NEntry.first_inpatient_visit', index=19,
      number=29, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vtype_count', full_name='comphealth.NEntry.vtype_count', index=20,
      number=30, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=666,
)


_N4VCOUNT = _descriptor.Descriptor(
  name='N4VCOUNT',
  full_name='comphealth.N4VCOUNT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k', full_name='comphealth.N4VCOUNT.k', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IP', full_name='comphealth.N4VCOUNT.IP', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ED', full_name='comphealth.N4VCOUNT.ED', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AS', full_name='comphealth.N4VCOUNT.AS', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=668,
  serialized_end=725,
)

_NENTRY.fields_by_name['index_first_days'].message_type = pstat_pb2._INTHIST
_NENTRY.fields_by_name['sub_first_days'].message_type = pstat_pb2._INTHIST
_NENTRY.fields_by_name['dxh'].message_type = pstat_pb2._DXI
_NENTRY.fields_by_name['primary_prh'].message_type = pvisit_pb2._KVI
_NENTRY.fields_by_name['prh'].message_type = pvisit_pb2._KVI
_NENTRY.fields_by_name['exh'].message_type = pvisit_pb2._KVI
_NENTRY.fields_by_name['drgh'].message_type = pvisit_pb2._KVI
_NENTRY.fields_by_name['first_inpatient_visit'].message_type = pstat_pb2._AGG
_NENTRY.fields_by_name['vtype_count'].message_type = _N4VCOUNT
DESCRIPTOR.message_types_by_name['NEntry'] = _NENTRY
DESCRIPTOR.message_types_by_name['N4VCOUNT'] = _N4VCOUNT

NEntry = _reflection.GeneratedProtocolMessageType('NEntry', (_message.Message,), dict(
  DESCRIPTOR = _NENTRY,
  __module__ = 'pn4_pb2'
  # @@protoc_insertion_point(class_scope:comphealth.NEntry)
  ))
_sym_db.RegisterMessage(NEntry)

N4VCOUNT = _reflection.GeneratedProtocolMessageType('N4VCOUNT', (_message.Message,), dict(
  DESCRIPTOR = _N4VCOUNT,
  __module__ = 'pn4_pb2'
  # @@protoc_insertion_point(class_scope:comphealth.N4VCOUNT)
  ))
_sym_db.RegisterMessage(N4VCOUNT)


# @@protoc_insertion_point(module_scope)
